name: Windows CI

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  ci-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]
    name: Windows CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Run ${{ matrix.python-version }} platform tests (default)
        uses: py-actions/py-dependency-install@master
        with:
          path: "tests/requirements.txt"
      - name: Run ${{ matrix.python-version }} platform tests (with args)
        uses: py-actions/py-dependency-install@master
        with:
          path: "tests/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
